name: SonarQube Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 网页可手动触发

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PATH: /opt/sonar-scanner/bin:$PATH   # 保证 runner 能找到 sonar-scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=VideoSemanticCompressed \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://192.168.220.128:9000 \
            -Dsonar.login=$SONAR_TOKEN
